<LoginScreen>
    quote_of_the_day: quote_of_the_day
    emp_id: emp_id

    MDLabel:
        id: quote_of_the_day
        pos_hint: {"center_y": .25, "center_x": .5}
        font_size: 15
        halign: "center"
        color: "lightblue"


    MDTextField:
        id: emp_id
        hint_text: "Enter Employee ID"
        focus: False
        font_size: 25
        pos_hint: {"center_x": .5, "center_y": .5}
        size_hint: .15, .085
        password: True

